---
name: bosh

releases:
- name: bosh
  url: file:///home/cf/workspace/releases/bosh-release-257.15.tgz
  sha1: f4cf3579bfac994cd3bde4a9d8cbee3ad189c8b2
- name: bosh-openstack-cpi
  url: file:///home/cf/workspace/releases/bosh-openstack-cpi-release-27.tgz
  sha1: 85e6244978f775c888bbd303b874a2c158eb43c4

resource_pools:
- name: vms
  network: private
  stemcell:
    url: file:///home/cf/workspace/stemcells/bosh-stemcell-3312.12-openstack-kvm-ubuntu-trusty-go_agent-raw.tgz
    sha1: dc98bec2e801fb5e29cbe6cca512f30ec01181ca
  cloud_properties:
    instance_type: m1.medium

disk_pools:
- name: disks
  disk_size: 80_000

networks:
- name: private
  type: manual
  subnets:
  - range: 192.168.100.0/24 # <--- Replace with a private subnet CIDR
    gateway: 192.168.100.1 # <--- Replace with a private subnet's gateway
    dns: [172.16.1.1] # <--- Replace with your DNS
    cloud_properties: {net_id: 3408e448-c0dd-4020-8603-9808cd3c764e} # <--- # Replace with private network UUID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: openstack_cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [192.168.100.20] # <--- Replace with a private IP
    default: [dns, gateway]
  - name: public
    static_ips: [172.16.1.20] # <--- Replace with a floating IP

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: 192.168.100.20 # <--- Replace with a private IP
      host: 192.168.100.20 # <--- Replace with a private IP
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 192.168.100.20 # <--- Replace with a private IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: openstack_cpi
      max_threads: 3
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    openstack: &openstack
      auth_url: http://172.16.1.109:5000/v2.0 # <--- Replace with OpenStack Identity API endpoint
      project: cf # <--- Replace with OpenStack project name
      domain: sys.chapter10.cn # <--- Replace with OpenStack domain name
      username: cf # <--- Replace with OpenStack username
      tenant: cf
      api_key: Chapter10io # <--- Replace with OpenStack password
      default_key_name: bosh
      default_security_groups: [bosh]

    agent: {mbus: "nats://nats:nats-password@192.168.100.20:4222"} # <--- Replace with a private IP

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  ssh_tunnel:
    host: 172.16.1.20 # <--- Replace with a floating IP
    port: 22
    user: vcap
    private_key: ./bosh.pem # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@172.16.1.20:6868" # <--- Replace with a floating IP

  properties:
    openstack: *openstack
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
