---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.15
  sha1: f4cf3579bfac994cd3bde4a9d8cbee3ad189c8b2
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=26
  sha1: 09c18a410aca8a15c11fcbe028f3eac39bef31b5

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3263.8
    sha1: 3585a7d5239107a4728c8601517dbba0a416378a
  cloud_properties:
    instance_type: m1.xlarge

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: 192.168.100.0/24 # <--- Replace with a private subnet CIDR
    gateway: 192.168.100.1 # <--- Replace with a private subnet's gateway
    dns: [10.152.2.10] # <--- Replace with your DNS
    cloud_properties: {net_id: 953e34d3-7d5f-4f3c-82af-e5e5587c1561} # <--- # Replace with private network UUID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: openstack_cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [192.168.100.20] # <--- Replace with a private IP
    default: [dns, gateway]
  - name: public
    static_ips: [10.152.11.43] # <--- Replace with a floating IP

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: 192.168.100.20 # <--- Replace with a private IP
      host: 192.168.100.20 # <--- Replace with a private IP
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 192.168.100.20 # <--- Replace with a private IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: openstack_cpi
      max_threads: 3
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    openstack: &openstack
      auth_url: http://10.152.11.30:5000/v2.0 # <--- Replace with OpenStack Identity API endpoint
      project: cf # <--- Replace with OpenStack project name
      domain: 10.152.11.30.xip.io # <--- Replace with OpenStack domain name
      username: cf # <--- Replace with OpenStack username
      tenant: cf
      api_key: cetas123 # <--- Replace with OpenStack password
      default_key_name: bosh
      default_security_groups: [bosh]

    agent: {mbus: "nats://nats:nats-password@192.168.100.20:4222"} # <--- Replace with a private IP

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  ssh_tunnel:
    host: 10.152.11.43 # <--- Replace with a floating IP
    port: 22
    user: vcap
    private_key: ./bosh.key # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@10.152.11.43:6868" # <--- Replace with a floating IP

  properties:
    openstack: *openstack
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
